export const metadata = {
  title: "Terms of Use | Zipply",
  description: "Terms of Use for Zipply URL shortener.",
};

export default function TermsOfUsePage() {
  return (
    <div className="container mx-auto px-4 sm:px-6 py-12 sm:py-16 md:py-24 max-w-3xl">
        <h1 className="text-3xl sm:text-4xl md:text-5xl font-extrabold tracking-tighter mb-6 sm:mb-8">
          Terms of Use
        </h1>
        <div className="prose prose-sm sm:prose-base prose-neutral dark:prose-invert max-w-none text-muted-foreground font-medium leading-relaxed space-y-4 sm:space-y-6">
          <p>
            Last updated: {new Date().toLocaleDateString("en-US", { month: "long", year: "numeric", day: "numeric" })}
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-12 mb-4 tracking-tight">1. Acceptance of Terms</h2>
          <p>
            By accessing or using the Zipply service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you do not have permission to access the Service.
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-12 mb-4 tracking-tight">2. Use of Service</h2>
          <p>
            You agree to use our URL shortening services strictly for lawful purposes. You shall not use Zipply to point to malicious, illegal, or spam-oriented websites (including phishing and malware hosting). We reserve the right to instantly terminate any links or accounts that violate this rule without prior notice.
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-12 mb-4 tracking-tight">3. User Accounts</h2>
          <p>
            When you create an account with us, you must provide information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service. You are responsible for safeguarding the password that you use to access the Service.
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-12 mb-4 tracking-tight">4. Intellectual Property</h2>
          <p>
            The Service and its original content (excluding links generated by users), features, and functionality are and will remain the exclusive property of Zipply and its licensors.
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-12 mb-4 tracking-tight">5. Limitation of Liability</h2>
          <p>
            In no event shall Zipply, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
          </p>
        </div>
    </div>
  );
}
